--- migration:up
ALTER TABLE users
    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;

SELECT setval(
    pg_get_serial_sequence('users', 'id'),
    COALESCE((SELECT MAX(id) FROM users), 0) + 1,
    false
);

ALTER TABLE users
    ADD CONSTRAINT users_ip_address_key UNIQUE (ip_address);

--- migration:down
ALTER TABLE users
    DROP CONSTRAINT users_ip_address_key;

ALTER TABLE users
    ALTER COLUMN id DROP IDENTITY IF EXISTS;
--- migration:end
