services:

  server:
    container_name: killmestats
    build:
      context: .
      dockerfile: server/Dockerfile
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB}
      POSTGRES_HOST: postgres

